tug_turtlebot4:
  static_transform_publisher:
    ros__parameters:
      from:
        - "odom"
        - "odom"
        - "tug_turtlebot4"
      to:
        - "columns"
        - "maze"
        - "base_link"